version: "3"

services:
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: test
    ports:
      - 3306:3306