spring:
  application:
    name: call-detail-record
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&rewriteBatchedStatements=true
    username: db_user
    password: db_password
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB


call:
  details:
    import:
      batch-size: 10000